name: Check Submission

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Validate single file submission
        run: |
          # Get the list of changed files (space-separated).
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"

          # Convert to an array so we can count easily.
          changed_files_array=($changed_files)
          file_count=${#changed_files_array[@]}

          # Check that exactly one file changed.
          if [ "$file_count" -ne 1 ]; then
            echo "Error: Exactly one file must be changed or created, found $file_count."
            exit 1
          fi

          # Check that the file name matches submissions/<username>.py
          file="${changed_files_array[0]}"
          expected="submissions/${{ github.actor }}.py"

          if [ "$file" != "$expected" ]; then
            echo "Error: The submission file must be located at '$expected'. Found: $file"
            exit 1
          fi

          echo "Success: Exactly one file changed, named '$expected'."
